name: GitHub Actions
run-name: Deploy github actions 🚀
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - merged
    branches:
      - main
jobs:
  deploy_github_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ${{ github.repository }} repository
        uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - run: yarn export
      - name: setting for deploy
        run: cd out && echo 'azisong.com' > CNAME && touch .nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out
      - run: echo "This job's status is ${{ job.status }}."
